-- Add missing columns to magazines table
USE trendorabay;

ALTER TABLE magazines 
ADD COLUMN IF NOT EXISTS description TEXT,
ADD COLUMN IF NOT EXISTS price DECIMAL(10, 2),
ADD COLUMN IF NOT EXISTS digital_price DECIMAL(10, 2),
ADD COLUMN IF NOT EXISTS print_price DECIMAL(10, 2),
ADD COLUMN IF NOT EXISTS subscription_price DECIMAL(10, 2),
ADD COLUMN IF NOT EXISTS pages INT,
ADD COLUMN IF NOT EXISTS language VARCHAR(50),
ADD COLUMN IF NOT EXISTS publisher VARCHAR(255),
ADD COLUMN IF NOT EXISTS rating DECIMAL(3, 2),
ADD COLUMN IF NOT EXISTS review_count INT DEFAULT 0,
ADD COLUMN IF NOT EXISTS table_of_contents TEXT,
ADD COLUMN IF NOT EXISTS contributors TEXT,
ADD COLUMN IF NOT EXISTS preview_pages TEXT;
